[workspace]
members = [
    "elements-harness",
    "swap",
    "bobtimus",
    "covenants",
    "extension",
    "extension/message_types",
    "extension/wallet_lib",
    "extension/background",
    "extension/content",
    "extension/in_page",
    "extension/wasm_bindgen_extension"
]

[patch.crates-io]
# Until https://github.com/ElementsProject/rust-elements/pull/70/ is merged
elements = { path = "/Users/bonomat/src/github/luckysori/rust-elements" }