[package]
name = "wasm-bindgen-extension"
version = "0.1.0"
authors = [ "CoBloX Team <team@coblox.tech>" ]
edition = "2018"

[dependencies]
js-sys = "0.3"
serde = { version = "1.0", features = [ "derive" ] }
wasm-bindgen = { version = "0.2", features = [ "serde-serialize" ] }
web-sys = "0.3"
