[package]
name = "covenants"
version = "0.1.0"
authors = ["Philipp Hoenisch <philipp@hoenisch.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elements-harness = {path= "../elements-harness"}
elements = "0.15"
testcontainers = "0.11"
tokio = { version = "1", default-features = false, features = [ "macros", "rt", "time" ] }